### ISSUE TITLE
Betonquest Issue

### ISSUE THREAD

**Issue by SaltyAimbOtter** [MartenM/ServerTutorialPlus#12]
I want to run the /st play <Tutorial> <Player> from console for improved automatisation in my server.
This could also be solved by providing Betonquest support (e.g. add new event to that plugin that starts a tutorial)

**Comment by MartenM** [comment]
Not sure about adding full support for something like that, but this command might help you: `/st play <id> (playername)`

**Comment by SaltyAimbOtter** [comment]
Yeah i used this command. I let it execute from the console but this seems not to be allowed.

**Comment by MartenM** [comment]
@SaltyAimbOtter oh, that's weird. I will take a look at it.

**Comment by MartenM** [comment]
Found the issue, the consol is not allowed to execute the command. Will fix shortly.

**Comment by MartenM** [comment]
> This could also be solved by providing Betonquest support (e.g. add new event to that plugin that starts a tutorial)

If still want to suggest this, please create a new issue ;)
