### ISSUE TITLE
1.14 Problem Particle REDSTONE requires data, null provided

### ISSUE THREAD

**Issue by Blueeyestar** [MartenM/ServerTutorialPlus#19]
Spigotversion:CraftBukkit version git-Spigot-1eece4f-8ddb94d (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

**Hello, I wanted to ask if there will be a plugin in the 1.14 as well. It has helped many users and would be a pity if it doesn't come anymore.

Many errors are thrown out in 1.14**

https://pastebin.com/eHv1DZru

**Comment by MartenM** [comment]
Fixed in 1.14 releases.
