### ISSUE TITLE
GUI Bug

### ISSUE THREAD

**Issue by Aeyori** [MartenM/ServerTutorialPlus#23]
Error when trying to use GUI

## The problem

I get an error in the console when I try to access the tutorial gui. When I click on the apple it gives me this error
https://pastebin.com/EC5Z4DUX
## Possible Solution

Coding error somewhere
## Steps to Reproduce

1. Do /st tutorial
2. click on the apple

**Comment by MartenM** [comment]
GUI is a removed feature and it won't be coming back.
Still need to remove some parts of it though.

**Comment by MartenM** [comment]
Fixed in the latest release!
