### ISSUE TITLE
Can't move after reloading the plugin while beeing in a tutorial

### ISSUE THREAD

**Issue by BijuuKrunos** [MartenM/ServerTutorialPlus#24]
Reproduce: Go in a tutorial with locplayer: true. Do /st reload.
Result: You will be stuck and cannot move anymore. 

How to solve: You have to delete your playerdata.dat

**Comment by MartenM** [comment]
This issue can also be resolved by doing /speed 1 if you have essentials installed.

Good find though. Will patch when I have time.

**Comment by BijuuKrunos** [comment]
ihhh Essentials. bähhh 

I am using external inventories so i can delete the playerdata without lost.
But yeah fix would be great.

thx.

**Comment by MartenM** [comment]
Fixed in the latest release!
