### ISSUE TITLE
NPC, NPC list and more...

### ISSUE THREAD

**Issue by SmajliceKsM** [MartenM/ServerTutorialPlus#37]
Hi, after writing the command /st npc add ... npc only flashes and disappears right away... 

The server runs at 1.16.2 and I have a Citizens plugin as well. 

After the creation of the NPC by order it did not deposit in my yml and I cannot delete the hologram now... 

It doesn't work /st npc list, it still only shows me commands I can use after writing the command... 

The /st gui command no longer works? If not, then why is he in the list ? And if it works, I don't know why he's texting me that he's not supported.

I notice that if I set the fly to true at the tutor, then after the finish everyone is still allowed and I have to manually turn it off for them.

**Comment by kalebbroo** [comment]
Were you able to figure out how to remove the text over the npc that disappeared? I am having the same issue.

**Comment by MartenM** [comment]
I will look into this issue the coming week hopefully.

**Comment by kalebbroo** [comment]
@SmajliceKsM I was finally able to remove it by using this.

/minecraft:kill @e[type=minecraft:armor_stand,sort=nearest,limit=2]

**Comment by isaaclepes** [comment]
I am encountering this issue as well.  There are a select few NPC types that work, but none of the others do.
List of working NPC types in 1.16.5 PaperMC:
Pig
Sheep
Wolf
Polar Bear
Horse
Villager
Chicken
Rabbit
Bat

**Comment by isaaclepes** [comment]
Update:  My issue was caused by difficulty being set to peaceful.

**Comment by MartenM** [comment]
Checking is now done to prevent issues like these occuring.
