### ISSUE TITLE
New feature: Can't see others chatting during tutorial

### ISSUE THREAD

**Issue by Krosta8** [MartenM/ServerTutorialPlus#4]
Hi,
I couldn't remember, where I wrote it to you, about the option for not to see others in chat during tutorial, so I decided to wrote it here, to issues.

The problem is, that if you have server with a lot of people online and you want to use chat info during tutorial, the player is almost unable to see this messages, because of the spam in chat.

Solution for this:
At the moment of joining tutorial, player can see messages only from the tutorial. Nothing else. 
Without this option are chat messages unuseful for us.

Thank you for reading this :)

**Comment by MartenM** [comment]
Thanks for making creating this thread on GitHub.  Makes it easier for me to keep track of things.

I will look into this if I get some spare time.

**Comment by Sprungente** [comment]
It's nice when every input from Chats will be disabled for this moment. Maybe Chatmessages from bungeecord too. That will be awesome!

**Comment by MartenM** [comment]
I can block incoming messages from other people for sure. Bungeecord will simply not be possible due to the fact that those messages do not even cross the server (**player <-> bungee** <-> server).

**Comment by MartenM** [comment]
On another note, if this were to be implemented, would you guys to see this as a **per point option** or specify it **per tutorial**?

**Comment by xion87** [comment]
per tutorial would be ok :)

**Comment by Golicraft** [comment]
Lovely! Excited for this feature too

**Comment by MartenM** [comment]
This feature has been implemented.
