### ISSUE TITLE
Help with an question

### ISSUE THREAD

**Issue by LordLucass** [MartenM/ServerTutorialPlus#40]
Hello, I don't know if this is really a problem, but I would like to know what parameter I can use to identify the player who is using ServerTutorialPlus at the moment, I tried to use% player% and I couldn't, could you tell me?

![Screenshot_1](https://user-images.githubusercontent.com/47451974/96327751-844c9800-1012-11eb-945c-07b183e4c203.png)

**Comment by MartenM** [comment]
From the spigot resource page: ```{player_name}```

**Comment by LordLucass** [comment]
Thank u

**Comment by LordLucass** [comment]
Is it possible for me to edit the tutorial from the yaml file without deleting it?

**Comment by MartenM** [comment]
1. Stop the server
2. Back up the file
3. Edit the file
4.  Start the server again

**Comment by LordLucass** [comment]
Thank u
