### ISSUE TITLE
Right-click on CLICK_BLOCK misbehaves

### ISSUE THREAD

**Issue by SlimeDog** [MartenM/ServerTutorialPlus#44]
## The problem

Spigot 1.16.5-3028 or Paper 1.16.5-565 (and many versions prior)
ServerTutorialPlus 1.21.5

I have encountered an anomaly. It may have always been true, or may be related to a click-handling change in 1.16.5. When running a tutorial, when a player right-clicks on a CLICK_BLOCK with an item -- i.e., with a non-empty hand, for example a sword or axe -- the player skips a step in the tutorial. It is almost as if the right-click is processed twice. (If the player right-clicks with an empty hand, or left-clicks with the same item, the steps progress as configured.) All steps are CLICK_BLOCK activated.

Also see related [feature request](https://github.com/MartenM/ServerTutorialPlus/issues/45).

## Steps to Reproduce

1. Create tutorial, as linked below. Each step has a CLICK_BLOCK, which is a single black_stained_glass_pane atop a single iron_bars (an image is appended).
2. Start the tutorial.
3. At any point, right-click on a CLICK_BLOCK with a sword or axe or ...
4. Observe that a step is skipped. The steps are numbered in the subtitles, to make this clear.

## Sample tutorial
[http://blackdog.straight8.com/drops/tutorialsaves.yml](http://blackdog.straight8.com/drops/tutorialsaves.yml)

## Images
![Screen Shot 2021-03-23 at 2 20 40 AM](https://user-images.githubusercontent.com/17748923/112123343-6a455180-8b7e-11eb-96a2-44e985bf9098.png)

**Comment by SlimeDog** [comment]
Is this included in STP 1.23.5 ?

**Comment by MartenM** [comment]
Now released in 1.24.0

**Comment by SlimeDog** [comment]
Thanks.
