### ISSUE TITLE
port of mysql

### ISSUE THREAD

**Issue by bighead0901** [MartenM/ServerTutorialPlus#49]
May I know if I can change the port of SQL in config? Because it seems it is fixed in the code.

 ```config.setJdbcUrl(String.format("jdbc:mysql://%s:%s/%s", host, 3306, database));```

**Comment by MartenM** [comment]
When I did the refactor the MySql driver I noticed this too but didn't think too much of it.

I will see if I can change this sometime soon. Currently very busy though so if a PR would be made to add this that would work great too :)

**Comment by MartenM** [comment]
Closed by commit 0db307b6bf405c6da79995f9c09fe2a6032050d7.
