### ISSUE TITLE
Plugin not responding to commands anymore

### ISSUE THREAD

**Issue by VerguchtNiels** [MartenM/ServerTutorialPlus#7]
## The problem
![image](https://user-images.githubusercontent.com/16087251/46906128-eb548500-cefe-11e8-97b5-0fe925fa0893.png)
The plugin worked perfectly at the start, no problems at all and helped me out a lot for new players. But since yesterday it just stopped responding to any command. As you can see in the image the plugin loads completely fine and finds my tutorial.

## Steps to Reproduce
1. Start server like usual

**Comment by MartenM** [comment]
Closing this due to no response.
